### ISSUE TITLE
`std::iter::IntoIterator::Item` vs `CollectionTrait::ElemType` mismatch

### ISSUE THREAD

**Issue by MingweiSamuel** [Airtnp/collection_traits#1]
https://github.com/Airtnp/collection_traits/blob/ca569a64acf8d3a927ed0be39e3a0fb322849a63/src/iter.rs#L7-L8

Should this be
```rs
pub trait Iterable: CollectionTrait + IntoIterator<Item = Self::ElemType> {
```
To guarantee that the item types match?

**Comment by Airtnp** [comment]
Thanks for good catch. Actually, I lift the `IntoIterator` requirement to `Collection` so that would be redundant here.
